#!/bin/sh -f

#
# rpg - random palette generator
#

seq() {
    seqs="$seqs]$1;$2\\";

    case $1 in
        *";"*)
            [ "${1##*;}" -lt 16 ] && {
                printf '%s\n' "color${1##*;}=\"$2\"" >> "$cache_dir/colors"
            }
        ;;
    esac
}

exists() {
    command -v "$1" >/dev/null
}

runs() {
    pgrep -x "$1" >/dev/null
}

rgb() {
    # shellcheck disable=SC2046
    set -- $(shuf -i "$1"-"$2" -n 1)

    printf '%02x\n' "$1"
}

hex() {
    min=120
    max=180

    [ "$light" ] && {
        min=100
        max=160
    }

    r=$(rgb "${1:-$min}" "${2:-$max}")
    g=$(rgb "${3:-$min}" "${4:-$max}")
    b=$(rgb "${5:-$min}" "${6:-$max}")

    printf '#%s%s%s\n' "$r" "$g" "$b"
}


current() {
    printf '\n'

    # This nifty thrifty syntax is borrowed from:
    # https://github.com/dylanaraps/bin/blob/c06b2c0df0194487fc4cb9c65b451b6369e2c398/shuffle#L17
    for i in 1 2 3 4 5 6 7; do
        printf '\033[4%sm  \033[m ' "$i"
    done

    printf '\n\n'

    exit
}

palette() {
    bg="$(hex "20" "30" "30" "40" "40" "50")"
    fg="$(hex "220" "230" "230" "240" "240" "250")"
    black="$(hex "60" "70" "70" "80" "80" "90")"

    [ "$light" ] && {
        bg="$(hex "245" "250" "245" "250" "245" "250")"
        fg="$(hex "40" "50" "50" "60" "60" "70")"
        black="$(hex "170" "180" "170" "180" "170" "180")"
    }

    red="$(hex)"
    green="$(hex)"
    yellow="$(hex)"
    blue="$(hex)"
    magenta="$(hex)"
    cyan="$(hex)"
}

sequences() {
    # Regular colors
    seq "4;0" "$bg"
    seq "4;1" "$red"
    seq "4;2" "$green"
    seq "4;3" "$yellow"
    seq "4;4" "$blue"
    seq "4;5" "$magenta"
    seq "4;6" "$cyan"
    seq "4;7" "$fg"
    seq "4;8" "$black"
    seq "4;9" "$red"
    seq "4;10" "$green"
    seq "4;11" "$yellow"
    seq "4;12" "$blue"
    seq "4;13" "$magenta"
    seq "4;14" "$cyan"
    seq "4;15" "$fg"

    # Special colors
    # 10:  Foreground color
    # 11:  Background color
    # 12:  Cursor foreground color
    # 13:  Mouse foreground color
    # 17:  Highlight background Color
    # 19:  Highlight foreground Color
    # 256: Cursor color
    # 257: Reversed cursor color
    # 258: Background color
    # 259: Foreground color
    seq "10" "$fg"
    seq "11" "$bg"
    seq "12" "$fg"
    seq "13" "$fg"
    seq "17" "$bg"
    seq "19" "$fg"
    seq "4;256" "$fg"
    seq "4;257" "$bg"
    seq "4;258" "$bg"
    seq "4;259" "$fg"

    # Unless VTE
    # 708: Border color
    [ "$VTE_VERSION" ] || seq "708" "$bg"
}

wallpaper() {
    if runs "picom" || runs "compton"; then
        exists "hsetroot" && hsetroot -solid "$black"
    else
        exists "xsetroot" && xsetroot -solid "$black"
    fi
}

activate() {
    set +f
    set -f -- /dev/pts/[0-9]*
    for tty in "$@"; do
        [ -w "$tty" ] && printf %b "$seqs" > "$tty" &
    done

    printf %b "$seqs" > "$cache_dir/sequences"
}

main() {
    mkdir -p "${cache_dir:=$HOME/.cache/rpg}"

    case $1 in
        d|dark) ;;
        l|light) light=1 ;;
        r|reload) cat "$cache_dir/sequences" 2>/dev/null; exit ;;
        c|current) current ;;
        *) printf '%s\n' \
            "Usage: rpg [OPTION]" \
            "  d, dark       Generate dark palette" \
            "  l, light      Generate light palette" \
            "  r, reload     Reload current palette" \
            "  c, current    Print current palette"
            exit
        ;;
    esac

    :> "$cache_dir/colors"

    palette

    sequences

    wallpaper

    activate

    current
}

main "$@"
